/FROM python:3.10

FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl
RUN apt-get upgrade -y

COPY <source> <destination>

ENTRYPOINT ["node","main.js"]





//docker build -t <imageName> .: to build an image.